//AQUI ESTAMOS CRIANDO VARIAVEIS GLOBAIS PARA TER ACESSO EM QUALQUER LUGAR DA NOSSA APLICAÇÃO
//UMA PARA HASH DE SENHA E AUTENTICAÇÃO E OUTRA PARA ENVIOU DE EMAILS UM EXEMPLO TEMPLATE
global.SALT_KEY = 'f5b99242-6504-4ca3-90f2-05e78e5761ef';


//AQUI ESTAMOS CRIANDO NOSSA CONECTSTRING DO BANCO DE DADOS
module.exports = {
    //STRING CONEXÃO COM BANCO
    connectionString: 'mongodb://localhost:27017/NodeBlog?readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=false',
}